apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # deployment labels
  labels:
    purpose: ingress 
    project: roboshop 
    app: app1
spec:
  replicas: 2
# These are the labels replica set use to create pod replicas, This should match pod labels.
  selector:
    matchLabels:
      purpose: ingress 
      project: roboshop 
      app: app1
  template:
  # This pod defination
    metadata:
      labels:
        purpose: ingress 
        project: roboshop 
        app: app1
    spec:
      containers:
      - name: app1
        image: sriharibandidevops/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: ingress 
    project: roboshop 
    app: app1
spec:
  selector:
    purpose: ingress 
    project: roboshop 
    app: app1
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: 80 #container port